include("C:/Users/samuel.barnett/Documents/repos/Mobagen/debug/cmake/CPM_0.38.2.cmake")
CPMAddPackage("NAME;SDL2;GITHUB_REPOSITORY;libsdl-org/SDL;GIT_TAG;release-2.26.2;OPTIONS;SDL2_DISABLE_INSTALL ON;SDL2_SHARED OFF;SDL_SHARED OFF;SDL_STATIC ON;SDL_STATIC_PIC ON;SDL_WERROR OFF;SDL_TEST OFF")
set(SDL2_FOUND TRUE)