include("C:/Users/samuel.barnett/Documents/repos/Mobagen/debug/cmake/CPM_0.38.2.cmake")
CPMAddPackage("GITHUB_REPOSITORY;libsdl-org/SDL_image;GIT_TAG;release-2.6.2;OPTIONS;BUILD_SHARED_LIBS OFF;SDL2_SHARED OFF;SDL_SHARED OFF;SDL2IMAGE_INSTALL OFF;SDL2IMAGE_SAMPLES OFF;SDL2IMAGE_VENDORED ON;SDL2IMAGE_BUILD_SHARED_LIBS OFF")
set(SDL_image_FOUND TRUE)